spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=root
spring.datasource.password=teamB

spring.sql.init.mode=always
spring.jpa.show-sql=true
