INSERT INTO category_m (category_id, category_name) VALUES
(1, '水'),
(2, 'お茶飲料'),
(3, 'コーヒー飲料'),
(4, '炭酸飲料'),
(5, '果実・野菜飲料'),
(6, 'スポーツ飲料'),
(7, '健康飲料'),
(8, 'エナジードリンク'),
(9, '乳性・乳酸菌飲料'),
(10, 'その他')
ON DUPLICATE KEY UPDATE
category_name = VALUES(category_name);

INSERT INTO product_m (
    product_id,
    product_name,
    product_quantity,
    product_image_url,
    category_id
) VALUES
(1, 'いろはす', 0, 'frontend/public/images/water/1.png', 1),
(2, 'アサヒ おいしい天然水', 0, 'frontend/public/images/water/2.png', 1),
(3, 'コントレックス', 0, 'frontend/public/images/water/3.png', 1),
(4, 'エビアン', 0, 'frontend/public/images/water/4.png', 1),
(5, 'クリスタルガイザー', 0, 'frontend/public/images/water/5.png', 1),
(6, '富士山の天然水', 0, 'frontend/public/images/water/6.png', 1),
(7, '白湯', 0, 'frontend/public/images/water/7.png', 1),
(8, '水素水', 0, 'frontend/public/images/water/8.png', 1),
(9, '綾鷹', 0, 'frontend/public/images/tea/9.png', 2),
(10, 'お〜いお茶', 0, 'frontend/public/images/tea/10.png', 2),
(11, '生茶', 0, 'frontend/public/images/tea/11.png', 2),
(12, '伊右衛門', 0, 'frontend/public/images/tea/12.png', 2),
(13, '健康ミネラル麦茶', 0, 'frontend/public/images/tea/13.png', 2),
(14, 'ルイボスティー', 0, 'frontend/public/images/tea/14.png', 2),
(15, 'ジャスミン茶', 0, 'frontend/public/images/tea/15.png', 2),
(16, '爽健美茶', 0, 'frontend/public/images/tea/16.png', 2),
(17, 'ミルクティー', 0, 'frontend/public/images/tea/17.png', 2),
(18, 'レモンティー', 0, 'frontend/public/images/tea/18.png', 2),
(19, 'クラフトボス無糖', 0, 'frontend/public/images/coffe/19.png', 3),
(20, 'ジョージアブラック', 0, 'frontend/public/images/coffe/20.png', 3),
(21, 'ジョージアカフェラテ', 0, 'frontend/public/images/coffe/21.png', 3),
 (22, 'コカ・コーラ', 0, 'frontend/public/images/carbonated/22.png', 4),
 (23, 'ペプシコーラ', 0, 'frontend/public/images/carbonated/23.png', 4),
 (24, 'スプライト', 0, 'frontend/public/images/carbonated/24.png', 4),
 (25, 'ファンタ', 0, 'frontend/public/images/carbonated/25.png', 4),
 (26, '三ツ矢サイダー', 0, 'frontend/public/images/carbonated/26.png', 4),
 (27, 'ウィルキンソン炭酸水', 0, 'frontend/public/images/carbonated/27.png', 4),
 (28, 'キリン キリッと果実', 0, 'frontend/public/images/fruits/28.png', 5),
 (29, '小岩井リンゴジュース', 0, 'frontend/public/images/fruits/29.png', 5),
 (30, 'Qooオレンジ', 0, 'frontend/public/images/fruits/30.png', 5),
 (31, '野菜生活', 0, 'frontend/public/images/fruits/31.png', 5),
 (32, 'トマトジュース', 0, 'frontend/public/images/fruits/32.png', 5),
 (33, 'Welch`s', 0, 'frontend/public/images/fruits/33.png', 5),
 (34, 'ポカリスエット', 0, 'frontend/public/images/sports/34.png', 6),
 (35, 'アクエリアス', 0, 'frontend/public/images/sports/35.png', 6),
 (36, 'OS-1', 0, 'frontend/public/images/sports/36.png', 6),
 (37, 'アミノサプリ', 0, 'frontend/public/images/sports/37.png', 6),
 (38, 'VAAM', 0, 'frontend/public/images/sports/38.png', 6),
 (39, 'ソルティライチ', 0, 'frontend/public/images/sports/39.png', 6),
 (40, 'ヤクルト', 0, 'frontend/public/images/health/40.png', 7),
 (41, 'リポビタンD', 0, 'frontend/public/images/health/41.png', 7),
 (42, 'ウコンの力', 0, 'frontend/public/images/health/42.png', 7),
 (43, 'モンスター', 0, 'frontend/public/images/energy/43.png', 8),
 (44, 'レッドブル', 0, 'frontend/public/images/energy/44.png', 8),
 (45, 'ZONE', 0, 'frontend/public/images/energy/45.png', 8),
 (46, 'カルピス', 0, 'frontend/public/images/milky/46.png', 9),
 (47, 'ぐんぐんぐると', 0, 'frontend/public/images/milky/47.png', 9),
 (48, 'ヨーグリーナ', 0, 'frontend/public/images/milky/48.png', 9),
 (49, 'いちごみるく', 0, 'frontend/public/images/milky/49.png', 9),
 (50, 'ソフトカツゲン', 0, 'frontend/public/images/milky/50.png', 9),
 (51, 'コーンポタージュ', 0, 'frontend/public/images/others/51.png', 10),
 (52, 'おしるこ', 0, 'frontend/public/images/others/52.png', 10),
 (53, '一風堂ラーメンスープ', 0, 'frontend/public/images/others/53.png', 10)
ON DUPLICATE KEY UPDATE
product_name = VALUES(product_name),
product_quantity = VALUES(product_quantity),
product_image_url = VALUES(product_image_url),
category_id = VALUES(category_id);

