INSERT INTO product_m (
    product_id,
    product_name,
    product_quantity,
    product_imageUrl,
    category_id
) VALUES
(1, 'いろはす', 0, 'frontend/public/images/water/1.jpeg', 1),
(2, 'アサヒ おいしい天然水', 0, 'frontend/public/images/water/2.jpeg', 1),
(3, 'コントレックス', 0, 'frontend/public/images/water/3.jpeg', 1),
(4, 'エビアン', 0, 'frontend/public/images/water/4.jpeg', 1),
(5, 'クリスタルガイザー', 0, 'frontend/public/images/water/5.jpeg', 1),
(6, '富士山の天然水', 0, 'frontend/public/images/water/6.jpeg', 1),
(7, '白湯', 0, 'frontend/public/images/water/7.jpeg', 1),
(8, '水素水', 0, 'frontend/public/images/water/8.jpeg', 1),
(9, '綾鷹', 0, 'frontend/public/images/tea/9.jpeg', 2),
(10, 'お〜いお茶', 0, 'frontend/public/images/tea/10.jpeg', 2),
(11, '生茶', 0, 'frontend/public/images/tea/11.jpeg', 2),
(12, '伊右衛門', 0, 'frontend/public/images/tea/12.jpeg', 2),
(13, '健康ミネラル麦茶', 0, 'frontend/public/images/tea/13.jpeg', 2),
(14, 'ルイボスティー', 0, 'frontend/public/images/tea/14.jpeg', 2),
(15, 'ジャスミン茶', 0, 'frontend/public/images/tea/15.jpeg', 2),
(16, '爽健美茶', 0, 'frontend/public/images/tea/16.jpeg', 2),
(17, 'ミルクティー', 0, 'frontend/public/images/tea/17.jpeg', 2),
(18, 'レモンティー', 0, 'frontend/public/images/tea/18.jpeg', 2),
(19, 'クラフトボス無糖', 0, 'frontend/public/images/coffe/19.jpeg', 3),
(20, 'ジョージアブラック', 0, 'frontend/public/images/coffe/20.jpeg', 3),
(21, 'ジョージアカフェラテ', 0, 'frontend/public/images/coffe/21.jpeg', 3),
 (22, 'コカ・コーラ', 0, 'frontend/public/images/carbonated/22.jpeg', 4),
 (23, 'ペプシコーラ', 0, 'frontend/public/images/carbonated/23.jpeg', 4),
 (24, 'スプライト', 0, 'frontend/public/images/carbonated/24.jpeg', 4),
 (25, 'ファンタ', 0, 'frontend/public/images/carbonated/25.jpeg', 4),
 (26, '三ツ矢サイダー', 0, 'frontend/public/images/carbonated/26.jpeg', 4),
 (27, 'ウィルキンソン炭酸水', 0, 'frontend/public/images/carbonated/27.jpeg', 4),
 (28, 'キリン キリッと果実', 0, 'frontend/public/images/fruits/28.jpeg', 5),
 (29, '小岩井リンゴジュース', 0, 'frontend/public/images/fruits/29.jpeg', 5),
 (30, 'Qooオレンジ', 0, 'frontend/public/images/fruits/30.jpeg', 5),
 (31, '野菜生活', 0, 'frontend/public/images/fruits/31.jpeg', 5),
 (32, 'トマトジュース', 0, 'frontend/public/images/fruits/32.jpeg', 5),
 (33, 'Welch`s', 0, 'frontend/public/images/fruits/33.jpeg', 5),
 (34, 'ポカリスエット', 0, 'frontend/public/images/sports/34.jpeg', 6),
 (35, 'アクエリアス', 0, 'frontend/public/images/sports/35.jpeg', 6),
 (36, 'OS-1', 0, 'frontend/public/images/sports/36.jpeg', 6),
 (37, 'アミノサプリ', 0, 'frontend/public/images/sports/37.jpeg', 6),
 (38, 'VAAM', 0, 'frontend/public/images/sports/38.jpeg', 6),
 (39, 'ソルティライチ', 0, 'frontend/public/images/sports/39.jpeg', 6),
 (40, 'ヤクルト', 0, 'frontend/public/images/health/40.jpeg', 7),
 (41, 'リポビタンD', 0, 'frontend/public/images/health/41.jpeg', 7),
 (42, 'ウコンの力', 0, 'frontend/public/images/health/42.jpeg', 7),
 (43, 'モンスター', 0, 'frontend/public/images/energy/43.jpeg', 8),
 (44, 'レッドブル', 0, 'frontend/public/images/energy/44.jpeg', 8),
 (45, 'ZONE', 0, 'frontend/public/images/energy/45.jpeg', 8),
 (46, 'カルピス', 0, 'frontend/public/images/milky/46.jpeg', 9),
 (47, 'ぐんぐんぐると', 0, 'frontend/public/images/milky/47.jpeg', 9),
 (48, 'ヨーグリーナ', 0, 'frontend/public/images/milky/48.jpeg', 9),
 (49, 'いちごみるく', 0, 'frontend/public/images/milky/49.jpeg', 9),
 (50, 'ソフトカツゲン', 0, 'frontend/public/images/milky/50.jpeg', 9),
 (51, 'コーンポタージュ', 0, 'frontend/public/images/others/51.jpeg', 10),
 (52, 'おしるこ', 0, 'frontend/public/images/others/52.jpeg', 10),
 (53, '一風堂ラーメンスープ', 0, 'frontend/public/images/others/53.jpeg', 10);

INSERT INTO category_m (category_id, category_name) VALUES
(1, '水'),
(2, 'お茶飲料'),
(3, 'コーヒー飲料'),
(4, '炭酸飲料'),
(5, '果実・野菜飲料'),
(6, 'スポーツ飲料'),
(7, '健康飲料'),
(8, 'エナジードリンク'),
(9, '乳性・乳酸菌飲料'),
(10, 'その他');